Emitting warnings for incoherent API doc elements
apidoc/apidoc pull request #1189
Opened 2022-03-17 19:10 UTC by Lucas-C

The goal of this PR is to generate warnings for inconsistent API doc comments.

For example, the following comment:
```javascript
/**
* @api {GET} /resource/:resId/sub/:subId getSubResource
* @apiParam {String} subId
*/
```

...would trigger this warning:
```
warn: URL contains a parameter ':resId' that is not documented as @apiParam in @api 'getSubResource' in file: 'api.js'
```

2022-03-17 22:38 UTC, NicolasCARPi requested changes
Hello, thank you for wanting to contribute to apidoc. Your proposition looks great. Could you please try and add a test case for your new code?

2022-03-18 12:33 UTC, Lucas-C commented
Sure, I have just added a unit test

2022-03-19 10:11 UTC, Lucas-C commented
The GitHub Actions pipeline is ✔️: https://github.com/voyages-sncf-technologies/apidoc/actions/runs/2008326289

2022-03-20 16:44 UTC, NicolasCARPi commented
We could even push further and add a warning if there is an api param that doesn't correspond to anything (so the other way around). Code that would emit a warning:

~~~js
/**
 * @api {get} /user/:id
 * @apiParam {Number} id user id
 * @apiParam {String} oops some leftover
 */
~~~

Would you be willing to add this to your PR?

2022-03-20 19:48 UTC, Lucas-C commented
OK, I also added that check

Pipeline is ✔️: https://github.com/voyages-sncf-technologies/apidoc/actions/runs/2012844549

2022-03-21 07:38 UTC, NicolasCARPi approved these changes
Thanks, great work!

2022-03-21 07:39 UTC, merged

2022-03-21 09:12 UTC, Lucas-C commented
Thank you for maintaining this lib, and for accepting my contribution 😊